spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false

  mongodb:
    uri: ${MONGO_DB_URI}

logging:
  level:
    root: INFO
    org.springframework.web.servlet.mvc.method.annotation.SseEmitter: DEBUG
    org.springframework.web.context.request.async: DEBUG
    com.example.TripMate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF