spring:
  application:
    name: TripMate
  config:
    import: optional:file:.env[.properties]
  jpa:
    open-in-view: false
  swagger-ui:
    tags-sorter: none
    operations-sorter: none
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}